# Generated by Django 3.0.7 on 2020-06-09 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geo', '0003_auto_20200608_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='SightseeingSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.Country')),
            ],
        ),
        migrations.CreateModel(
            name='SightSeeingSpotReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sightseeingSpot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.SightseeingSpot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
