#!/bin/sh
psql -U postgres -c "CREATE USER $POSTGRES_USER PASSWORD '$POSTGRES_PASSWORD'"
psql -U postgres -c "CREATE DATABASE $DB_NAME"
psql -U postgres -c "GRANT ALL ON DATABASE $DB_NAME TO $POSTGRES_USER;"
